/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.destrosul.view;

/**
 *
 * @author visitante
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public PrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        MenuOpenUsuario = new javax.swing.JMenuItem();
        MenuOpenProduto = new javax.swing.JMenuItem();
        MenuOpenPedido = new javax.swing.JMenuItem();
        MenuOpenCliente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        fileMenu.setMnemonic('f');
        fileMenu.setText("Cadastros");

        MenuOpenUsuario.setMnemonic('o');
        MenuOpenUsuario.setText("Usuário");
        MenuOpenUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOpenUsuarioActionPerformed(evt);
            }
        });
        fileMenu.add(MenuOpenUsuario);

        MenuOpenProduto.setMnemonic('s');
        MenuOpenProduto.setText("Produto");
        MenuOpenProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOpenProdutoActionPerformed(evt);
            }
        });
        fileMenu.add(MenuOpenProduto);

        MenuOpenPedido.setMnemonic('a');
        MenuOpenPedido.setText("Pedido");
        MenuOpenPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOpenPedidoActionPerformed(evt);
            }
        });
        fileMenu.add(MenuOpenPedido);

        MenuOpenCliente.setText("Cliente");
        MenuOpenCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOpenClienteActionPerformed(evt);
            }
        });
        fileMenu.add(MenuOpenCliente);

        menuBar.add(fileMenu);

        jMenu3.setText("Consultas");
        menuBar.add(jMenu3);

        jMenu2.setText("Relatórios");
        menuBar.add(jMenu2);

        jMenu1.setText("Ajuda");
        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuOpenClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOpenClienteActionPerformed
        ClienteView.main(null);
    }//GEN-LAST:event_MenuOpenClienteActionPerformed

    private void MenuOpenUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOpenUsuarioActionPerformed
        UsuarioView.main(null);
    }//GEN-LAST:event_MenuOpenUsuarioActionPerformed

    private void MenuOpenPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOpenPedidoActionPerformed
      PedidoView.main(null);
    }//GEN-LAST:event_MenuOpenPedidoActionPerformed

    private void MenuOpenProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOpenProdutoActionPerformed
      ProdutoView.main(null);
    }//GEN-LAST:event_MenuOpenProdutoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuOpenCliente;
    private javax.swing.JMenuItem MenuOpenPedido;
    private javax.swing.JMenuItem MenuOpenProduto;
    private javax.swing.JMenuItem MenuOpenUsuario;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
   private javax.swing.JDesktopPane desktopPane;
}
